import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import StyledComponentsRegistry from '@/lib/registry';
import PageLayout from '@/components/PageLayout';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <StyledComponentsRegistry>
          <PageLayout>{children}</PageLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
